"""
    KAKAPO - MSX SDK

    MSX Platform SDK  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import python_msx_sdk
from python_msx_sdk.model.device_billing import DeviceBilling


class TestDeviceBilling(unittest.TestCase):
    """DeviceBilling unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeviceBilling(self):
        """Test DeviceBilling"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DeviceBilling()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
