"""
    MSX SDK

    MSX SDK client.  # noqa: E501

    The version of the OpenAPI document: 1.0.10
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import python_msx_sdk
from python_msx_sdk.model.device_config_update import DeviceConfigUpdate


class TestDeviceConfigUpdate(unittest.TestCase):
    """DeviceConfigUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeviceConfigUpdate(self):
        """Test DeviceConfigUpdate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DeviceConfigUpdate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
