"""
    KAKAPO - MSX SDK

    MSX Platform SDK  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import python_msx_sdk
from python_msx_sdk.model.device_billing import DeviceBilling
from python_msx_sdk.model.device_create_all_of import DeviceCreateAllOf
from python_msx_sdk.model.device_update import DeviceUpdate
globals()['DeviceBilling'] = DeviceBilling
globals()['DeviceCreateAllOf'] = DeviceCreateAllOf
globals()['DeviceUpdate'] = DeviceUpdate
from python_msx_sdk.model.device_create import DeviceCreate


class TestDeviceCreate(unittest.TestCase):
    """DeviceCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeviceCreate(self):
        """Test DeviceCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DeviceCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
